{{-- Partial DRY para geração de slug automático --}}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const titleInput = document.getElementById('title');
        const slugInput = document.getElementById('id_slug');

        if (!titleInput || !slugInput) return;

        // Função para converter texto em slug
        function generateSlug(text) {
            return text
                .toString()
                .toLowerCase()
                .trim()
                .replace(/\s+/g, '-') // espaços em hífens
                .replace(/[^\w\-]+/g, '') // remove caracteres especiais
                .replace(/\-\-+/g, '-') // múltiplos hífens em um
                .replace(/^-+/, '') // remove hífens no início
                .replace(/-+$/, ''); // remove hífens no final
        }

        // Auto-preencher slug enquanto digita o título
        titleInput.addEventListener('input', function() {
            // Só auto-preenche se o slug estiver vazio ou for autogenerated
            if (slugInput.value === '' || slugInput.dataset.auto === 'true') {
                slugInput.value = generateSlug(this.value);
                slugInput.dataset.auto = 'true';
            }
        });

        // Marcar quando o usuário edita manualmente
        slugInput.addEventListener('input', function() {
            this.dataset.auto = 'false';
        });

        // Auto-gerar slug ao carregar se tiver título preenchido e slug vazio
        if (titleInput.value && !slugInput.value) {
            slugInput.value = generateSlug(titleInput.value);
            slugInput.dataset.auto = 'true';
        }
    });
</script>
